# Rakefile

require "fileutils"

namespace :generate do
  desc "Generate new folder day_xx with necessary files"
  task :day, [:day_number] do |t, args|
    day_number = args[:day_number].to_s.rjust(2, "0")
    folder_name = "day_#{day_number}"
    files = ["input.txt", "solution.rb", "test_solution.rb"]

    if Dir.exist?(folder_name)
      puts "Folder #{folder_name} already exists."
    else
      FileUtils.mkdir_p(folder_name)
      files.each do |file|
        FileUtils.touch(File.join(folder_name, file))
      end
      puts "Folder #{folder_name} with files #{files.join(", ")} created."
    end
  end
end


